// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
export default{
  "login": "devMuangi",
  "id": 55136496,
  "node_id": "MDQ6VXNlcjU1MTM2NDk2",
  "avatar_url": "https://avatars.githubusercontent.com/u/55136496?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/devMuangi",
  "html_url": "https://github.com/devMuangi",
  "followers_url": "https://api.github.com/users/devMuangi/followers",
  "following_url": "https://api.github.com/users/devMuangi/following{/other_user}",
  "gists_url": "https://api.github.com/users/devMuangi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/devMuangi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/devMuangi/subscriptions",
  "organizations_url": "https://api.github.com/users/devMuangi/orgs",
  "repos_url": "https://api.github.com/users/devMuangi/repos",
  "events_url": "https://api.github.com/users/devMuangi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/devMuangi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "devMuangi",
  "company": "codesmithsAfrica();",
  "blog": "devMuangi.github.io",
  "location": "kenya",
  "email": null,
  "hireable": true,
  "bio": "Making the world a better place through Code",
  "twitter_username": null,
  "public_repos": 45,
  "public_gists": 0,
  "followers": 6,
  "following": 14,
  "created_at": "2019-09-10T09:59:36Z",
  "updated_at": "2021-06-28T07:14:39Z"
};